# Dockerfile.dev

FROM node:18-slim

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./
RUN npm install

COPY .env .env

# Copy the rest of the app code
COPY . .

# Copy .env file to the runtime container
COPY .env .env

# Install development dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3010

# Run the development server
CMD ["npm", "run", "dev"]
