# Use a lightweight Node.js image
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

COPY .env .env

# Copy the rest of the app code
COPY . .

# Expose the port the app runs on
EXPOSE 3010

# Run the development server
CMD ["npm", "run", "dev"]
