// SKILLS
export const GET_SKILLS = "GET_SKILLS";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
export const GET_SKILLS_FAIL = "GET_SKILLS_FAIL";

// SKILLS
export const GET_EXPERIENCE = "GET_EXPERIENCE";
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_EXPERIENCE_FAIL = "GET_EXPERIENCE_FAIL";

export const GET_TECHNOLOGY = "GET_TECHNOLOGY";
export const GET_TECHNOLOGY_SUCCESS = "GET_TECHNOLOGY_SUCCESS";
export const GET_TECHNOLOGY_FAIL = "GET_TECHNOLOGY_FAIL";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
